CREATE FUNCTION formataCPF (`cpf` BIGINT( 11 ) UNSIGNED ZEROFILL) 
RETURNS VARCHAR( 14 ) 
DETERMINISTIC 
NO SQL 
SQL SECURITY DEFINER 
BEGIN 
RETURN CONCAT(SUBSTRING(cpf,1,3),'.',SUBSTRING(cpf,4,3),'.',SUBSTRING(cpf,7,3),'-',SUBSTRING(cpf,10,2));
END