CREATE FUNCTION formataCNPJ (`cnpj` BIGINT( 14 ) UNSIGNED ZEROFILL) 
RETURNS VARCHAR( 18 ) 
DETERMINISTIC 
NO SQL 
SQL SECURITY DEFINER 
BEGIN 
RETURN CONCAT(SUBSTRING(cnpj,1,2),'.',SUBSTRING(cnpj,3,3),'.',SUBSTRING(cnpj,6,3),'/',SUBSTRING(cnpj,9,4),'-',SUBSTRING(cnpj,13,2));
END